theme: jekyll-theme-minimal
title: وب توسعه‌ٔ فارسی
description: این تلاشی برای ایجاد بخشی از وب، بهینه‌سازی شده برای توسعه‌ٔ نرم‌افزار راست‌چین، کاربرپسند و مساعد برای توسعه‌دهندگان فارسی‌زبان بومی است.
